### PR TITLE
feat(rss): map charm members to their github profiles

### PR DESCRIPTION
**Pull request by bashbunni**
Add the team information to map blog post authors to team member's githubs

### CODE REVIEW

**Review by aymanbagabas — COMMENTED** [review]
I would keep this generic since we want people to use charmbracelet/markscribe as the canonical project

**Comment by bashbunni** [comment]
@aymanbagabas what would you suggest doing instead or where else could I put this (in the template file somehow?) that would make it more generic?

**Comment by ccoVeille** [comment]
> I would keep this generic since we want people to use charmbracelet/markscribe as the canonical project

I was also surprised by this addition to this package I thought to be generic and not charm based

**Comment by aymanbagabas** [comment]
> @aymanbagabas what would you suggest doing instead or where else could I put this (in the template file somehow?) that would make it more generic?

You could put them in the template file. With the help of go-sprout/sprig, we could map the Charm author from the RSS to their GitHub username 🙂

**Comment by bashbunni** [comment]
@aymanbagabas Thanks for pointing me in the right direction here! I did as you said using sprout and it works great. https://github.com/charmbracelet/.github/pull/5/files#diff-885b271153664f100985178e148d28687d6220474d93e4526bf5f9e17c5263d9R11

**Pull request closed without merging**
